/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourismIndexRouteImport } from './routes/tourism/index'
import { Route as TestimonialsIndexRouteImport } from './routes/testimonials/index'
import { Route as TourismAddRouteImport } from './routes/tourism/add'
import { Route as TestimonialsAddRouteImport } from './routes/testimonials/add'
import { Route as TourismIdEditRouteImport } from './routes/tourism/$id/edit'
import { Route as TestimonialsIdEditRouteImport } from './routes/testimonials/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismIndexRoute = TourismIndexRouteImport.update({
  id: '/tourism/',
  path: '/tourism/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIndexRoute = TestimonialsIndexRouteImport.update({
  id: '/testimonials/',
  path: '/testimonials/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismAddRoute = TourismAddRouteImport.update({
  id: '/tourism/add',
  path: '/tourism/add',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsAddRoute = TestimonialsAddRouteImport.update({
  id: '/testimonials/add',
  path: '/testimonials/add',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismIdEditRoute = TourismIdEditRouteImport.update({
  id: '/tourism/$id/edit',
  path: '/tourism/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIdEditRoute = TestimonialsIdEditRouteImport.update({
  id: '/testimonials/$id/edit',
  path: '/testimonials/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/testimonials/add': typeof TestimonialsAddRoute
  '/tourism/add': typeof TourismAddRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/tourism/': typeof TourismIndexRoute
  '/testimonials/$id/edit': typeof TestimonialsIdEditRoute
  '/tourism/$id/edit': typeof TourismIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/testimonials/add': typeof TestimonialsAddRoute
  '/tourism/add': typeof TourismAddRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/tourism': typeof TourismIndexRoute
  '/testimonials/$id/edit': typeof TestimonialsIdEditRoute
  '/tourism/$id/edit': typeof TourismIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/testimonials/add': typeof TestimonialsAddRoute
  '/tourism/add': typeof TourismAddRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/tourism/': typeof TourismIndexRoute
  '/testimonials/$id/edit': typeof TestimonialsIdEditRoute
  '/tourism/$id/edit': typeof TourismIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/testimonials/add'
    | '/tourism/add'
    | '/testimonials/'
    | '/tourism/'
    | '/testimonials/$id/edit'
    | '/tourism/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/testimonials/add'
    | '/tourism/add'
    | '/testimonials'
    | '/tourism'
    | '/testimonials/$id/edit'
    | '/tourism/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/testimonials/add'
    | '/tourism/add'
    | '/testimonials/'
    | '/tourism/'
    | '/testimonials/$id/edit'
    | '/tourism/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TestimonialsAddRoute: typeof TestimonialsAddRoute
  TourismAddRoute: typeof TourismAddRoute
  TestimonialsIndexRoute: typeof TestimonialsIndexRoute
  TourismIndexRoute: typeof TourismIndexRoute
  TestimonialsIdEditRoute: typeof TestimonialsIdEditRoute
  TourismIdEditRoute: typeof TourismIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism/': {
      id: '/tourism/'
      path: '/tourism'
      fullPath: '/tourism/'
      preLoaderRoute: typeof TourismIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/': {
      id: '/testimonials/'
      path: '/testimonials'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof TestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism/add': {
      id: '/tourism/add'
      path: '/tourism/add'
      fullPath: '/tourism/add'
      preLoaderRoute: typeof TourismAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/add': {
      id: '/testimonials/add'
      path: '/testimonials/add'
      fullPath: '/testimonials/add'
      preLoaderRoute: typeof TestimonialsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism/$id/edit': {
      id: '/tourism/$id/edit'
      path: '/tourism/$id/edit'
      fullPath: '/tourism/$id/edit'
      preLoaderRoute: typeof TourismIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/$id/edit': {
      id: '/testimonials/$id/edit'
      path: '/testimonials/$id/edit'
      fullPath: '/testimonials/$id/edit'
      preLoaderRoute: typeof TestimonialsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TestimonialsAddRoute: TestimonialsAddRoute,
  TourismAddRoute: TourismAddRoute,
  TestimonialsIndexRoute: TestimonialsIndexRoute,
  TourismIndexRoute: TourismIndexRoute,
  TestimonialsIdEditRoute: TestimonialsIdEditRoute,
  TourismIdEditRoute: TourismIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
